### ISSUE TITLE
DVC API wrapper considerations

### ISSUE THREAD

**Issue by yeraydavidrodriguez** [Nautilus-Cyberneering/nautilus-librarian#24]
We are using DVC as the first choice for remote storage of large files. This options was chosen by a number of reasons previously discussed.
Now we are on the process to move all the media management of the librarian to a monolithic Python codebase. Regarding DVC, this means moving from command line operations (typical usage of this tool, and how we have been using until now) to the usage of its [Python API](https://dvc.org/doc/api-reference). 
However, this API is extremely limited, and only exposes a few methods:
- **get_url**, to obtain the URL to the storage location of a tracked data file or directory.
- **open** a tracked file
- **read** the contents of a tracked file
- **make_checkpoint**, to create an [in-code checkpoint](https://dvc.org/doc/user-guide/experiment-management/checkpoints).

As DVC itself is written in Python and its internal methods and entities are directly used by this limited API, we decided to extend this API to cover the desired new functionality.
However, as works progressed, we see that the methods implemented by this new extended API are basically wrappers to _Repo_ class calls. Example:

```python
def openRepo(path):
    # error handling is omitted for clarity
    repo = Repo(path)
    return repo

def add(path, filename, recursive=False):
    repo = openRepo(path)
    return repo.add(filename, recursive=recursive)
```

Considering this, we have some options to consider:

1. Forget about this wrapper and directly use the internal DVC repo class to obtain the features uncovered by the DVC public API. As this internal Repo class is not a publicly exposed entity, if its functionality changes in an update, our code could break.
2. Finish the wrapper and add thorough tests, so that we can be aware of breaking changes in the functionality of the Repo object.
3. Rewrite current wrapper as an object-oriented API that extends DVC repo. Again, with tests, we would reduce the risk of breaking changes in the internal Repo object.
4. Keep using the DVC via shell commands from within the Python code.

I personally think that we should finish the wrapper as is being implemented. The wrapper functions are really easy to implement, and adding tests should not very costly neither. However, I would like to hear more opinions on this.

[Current wrapper implementation](https://github.com/Nautilus-Cyberneering/librarian/blob/issue-24-dvc-api-wrapper/src/nautilus_librarian/dvc_api.py) (preliminary) status can be checked on the [branch linked to this issue](https://github.com/Nautilus-Cyberneering/librarian/tree/issue-24-dvc-api-wrapper/).

**Comment by josecelano** [comment]
Just for clarification, option 3 would be something like: https://github.com/gitpython-developers/GitPython but we only implement the commands we need right now.
