### ISSUE TITLE
Delete Base image when Gold image is deleted

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/nautilus-librarian#49]
This is a subtask of this [issue-47](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/47)

In the last step of the [Gold Image Processing Workflow](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/src/nautilus_librarian/typer/commands/workflows/gold_images_processing.py) ([Auto-commit new Base images](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/src/nautilus_librarian/typer/commands/workflows/actions/auto_commit_base_images.py#L93)) we have not implemented some of the use cases yet.

This issue is for the Delete Use Case. It's not even mentioned in the [TODO list](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/src/nautilus_librarian/typer/commands/workflows/actions/auto_commit_base_images.py#L109-L124).

When a Gold image is deleted from dvc storage we have to delete the corresponding Base image (which was generated automatically when the Gold image was added).

Tasks:

- [ ] Chek is a Gold image was removed using `dvc diff`
- [ ] For each deleted image we should delete the Base image and create a new auto-commit for that change. One commit for each deleted image.

For the unit test, you can create a new dvc repo with a Gold and Base image, delete the Gold image and assert that the Base image was deleted after calling the action. Take a look at the [test for adding Gold images](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/tests/test_nautilus_librarian/test_typer/test_commands/test_workflows/test_actions/test_auto_commit_images.py#L62).

**Comment by josecelano** [comment]
Today we had a meeting and we defined the process for all the cases:

- When Gold Image is added
- When Gold Image is deleted
- When Gold Image is modified
- When Gold Image is renamed

I'm going to create a new issue describing the refactor we need for the "Auto-commit new Base images" action. Basically, we want to add info in a commit even if the cases are "empty". I mean, if no Gold image was added we should have a comment in the merge commit saying there was no Gold image added.

**Comment by yeraydavidrodriguez** [comment]
The base image is currently being deleted (implementation at [PR 73](https://github.com/Nautilus-Cyberneering/nautilus-librarian/pull/73)). There is still pending committing the deletion, that will be covered by #66 . We can close this issue now.
